defmodule AshPostgres.TestRepo.Migrations.MigrateResources21 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("post_followers", "post_followers_pkey"))

    alter table(:post_followers) do
      modify(:follower_id, :uuid, primary_key: true)
      modify(:post_id, :uuid, primary_key: true)

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :id
    end

    # 
    # 
  end

  def down do
    # Primary key removal is dropped because a corresponding attribute removal
    # has been commented out. If you uncomment this, uncomment the attribute removal and vice versa.
    # drop constraint("post_followers", "post_followers_pkey")
    # 
    alter table(:post_followers) do
      # This is the `down` migration of the statement:
      #
      #     remove :id
      #

      # add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      modify(:post_id, :uuid, primary_key: false)
      modify(:follower_id, :uuid, primary_key: false)
    end
  end
end
